STRINGS = GLOBAL.STRINGS
RECIPETABS = GLOBAL.RECIPETABS
Recipe = GLOBAL.Recipe
Ingredient = GLOBAL.Ingredient
TECH = GLOBAL.TECH

local multiplySpeedIncreaseFactor=30

TUNING.SPIDERDEN_GROW_TIME[1] = TUNING.SPIDERDEN_GROW_TIME[1]/multiplySpeedIncreaseFactor
TUNING.SPIDERDEN_GROW_TIME[2] = TUNING.SPIDERDEN_GROW_TIME[2]/multiplySpeedIncreaseFactor
TUNING.SPIDERDEN_GROW_TIME[3] = TUNING.SPIDERDEN_GROW_TIME[3]/multiplySpeedIncreaseFactor

TUNING.SPIDERQUEEN_DAMAGE = TUNING.SPIDERQUEEN_DAMAGE*2
TUNING.SPIDERQUEEN_HEALTH = TUNING.SPIDERQUEEN_HEALTH*2

