STRINGS = GLOBAL.STRINGS
RECIPETABS = GLOBAL.RECIPETABS
Recipe = GLOBAL.Recipe
Ingredient = GLOBAL.Ingredient
TECH = GLOBAL.TECH

local seg_time = 30
local total_day_time = seg_time*16

--Insulated Pack
--Only Lua Files

--Luxury Fan
TUNING.FEATHERFAN_COOLING = -70
TUNING.FEATHERFAN_USES = 25
TUNING.FEATHERFAN_RADIUS = 9
TUNING.FEATHERFAN_MINIMUM_TEMP = 1.5

--Weather Pain
TUNING.TORNADOSTAFF_USES = 25

--Hibearnation Vest
TUNING.BEARGERVEST_INSULATION = TUNING.INSULATION_LARGE*2

--Scail Mail
--TUNING.ARMORDRAGONFLY_FIRE_RESIST = 1 -- Already Max
TUNING.ARMORDRAGONFLY_ABSORPTION = 0.99
TUNING.ARMORDRAGONFLY = TUNING.ARMORDRAGONFLY * 1.5

--Scaled Chest
TUNING.SCALE_HAMMERHITS = 10

--Eyebrella
TUNING.EYEBRELLA_PERISHTIME = 15*total_day_time






