STRINGS = GLOBAL.STRINGS
RECIPETABS = GLOBAL.RECIPETABS
Recipe = GLOBAL.Recipe
Ingredient = GLOBAL.Ingredient
TECH = GLOBAL.TECH

local total_day_time = TUNING.TOTAL_DAY_TIME
local seg_time = TUNING.SEG_TIME

TUNING.PIG_DAMAGE = 50
TUNING.PIG_HEALTH = 350
TUNING.PIG_ATTACK_PERIOD = 4
TUNING.PIG_TARGET_DIST = 16
TUNING.PIG_LOYALTY_MAXTIME = 500 * total_day_time
TUNING.PIG_LOYALTY_PER_HUNGER = 1
TUNING.PIG_MIN_POOP_PERIOD = seg_time * 0.5

TUNING.PIG_HEALTH_PER_FOOD_STAT = 1

TUNING.WEREPIG_DAMAGE = TUNING.PIG_DAMAGE*3
TUNING.WEREPIG_HEALTH = TUNING.PIG_HEALTH*2
TUNING.WEREPIG_ATTACK_PERIOD = 2

TUNING.LEADER_VERIFY = "Leader!"

TUNING.TAME_MAX = 300



TUNING.BUNNYMAN_DAMAGE = 100
TUNING.BUNNYMAN_ATTACK_PERIOD = 2
TUNING.BUNNYMAN_HEALTH = 400

TUNING.CARROT_LOYALTY = 30

TUNING.BEARDLORD_DAMAGE = TUNING.BUNNYMAN_DAMAGE*2
