STRINGS = GLOBAL.STRINGS
RECIPETABS = GLOBAL.RECIPETABS
Recipe = GLOBAL.Recipe
Ingredient = GLOBAL.Ingredient
TECH = GLOBAL.TECH

TUNING.ONEMANBAND_PERISHTIME = 2*TUNING.TOTAL_DAY_TIME
TUNING.ONEMANBAND_MAX_FOLLOWERS = 16

TUNING.PIG_DAMAGE = 34
TUNING.HEALTH_PER_FOOD_STAT = 1

TUNING.BUNNYMAN_DAMAGE = 50
TUNING.BUNNYMAN_ATTACK_PERIOD = 2

