--Cold
return {
	override_enabled = true,
	preset = "SURVIVAL_TOGETHER", 			-- "SURVIVAL_TOGETHER", "MOD_MISSING", "SURVIVAL_TOGETHER_CLASSIC", "SURVIVAL_DEFAULT_PLUS", "COMPLETE_DARKNESS", "DST_CAVE", "DST_CAVE_PLUS"
	overrides = {
		-- MISC
		task_set = "default", 			-- "classic", "default", "cave_default"
		start_location = "default", 			-- "caves", "default", "plus", "darkness"
		world_size = "small", 			-- "small", "medium", "default", "huge"
		branching = "most", 			-- "never", "least", "default", "most"
		loop = "always", 			-- "never", "default", "always"
		autumn = "noseason", 			-- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
		winter = "longseason", 			-- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
		spring = "noseason", 			-- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
		summer = "noseason", 			-- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
		season_start = "winter", 			-- "default", "winter", "spring", "summer", "autumnorspring", "winterorsummer", "random"
		day = "onlynight", 			-- "default", "longday", "longdusk", "longnight", "noday", "nodusk", "nonight", "onlyday", "onlydusk", "onlynight"
		weather = "always", 			-- "never", "rare", "default", "often", "always"
		earthquakes = "default", 			-- "never", "rare", "default", "often", "always"
		lightning = "default", 			-- "never", "rare", "default", "often", "always"
		frograin = "default", 			-- "never", "rare", "default", "often", "always"
		wildfires = "never", 			-- "never", "rare", "default", "often", "always"
		touchstone = "default", 			-- "never", "rare", "default", "often", "always"
		regrowth = "veryslow", 			-- "veryslow", "slow", "default", "fast", "veryfast"
		cavelight = "default", 			-- "veryslow", "slow", "default", "fast", "veryfast"
		boons = "often", 			-- "never", "rare", "default", "often", "always"
		prefabswaps_start = "default", 			-- "classic", "default", "highly random"
		prefabswaps = "default", 			-- "none", "few", "default", "many", "max"

		-- RESOURCES
		flowers = "rare", 			-- "never", "rare", "default", "often", "always"
		grass = "rare", 			-- "never", "rare", "default", "often", "always"
		sapling = "default", 			-- "never", "rare", "default", "often", "always"
		marshbush = "default", 			-- "never", "rare", "default", "often", "always"
		tumbleweed = "never", 			-- "never", "rare", "default", "often", "always"
		reeds = "never", 			-- "never", "rare", "default", "often", "always"
		trees = "often", 			-- "never", "rare", "default", "often", "always"
		flint = "default", 			-- "never", "rare", "default", "often", "always"
		rock = "often", 			-- "never", "rare", "default", "often", "always"
		rock_ice = "default", 			-- "never", "rare", "default", "often", "always"
		meteorspawner = "default", 			-- "never", "rare", "default", "often", "always"
		meteorshowers = "default", 			-- "never", "rare", "default", "often", "always"
		mushtree = "default", 			-- "never", "rare", "default", "often", "always"
		fern = "default", 			-- "never", "rare", "default", "often", "always"
		flower_cave = "default", 			-- "never", "rare", "default", "often", "always"
		wormlights = "default", 			-- "never", "rare", "default", "often", "always"

		-- UNPREPARED
		berrybush = "never", 			-- "never", "rare", "default", "often", "always"
		carrot = "default", 			-- "never", "rare", "default", "often", "always"
		mushroom = "often", 			-- "never", "rare", "default", "often", "always"
		cactus = "never", 			-- "never", "rare", "default", "often", "always"
		banana = "never", 			-- "never", "rare", "default", "often", "always"
		lichen = "never", 			-- "never", "rare", "default", "often", "always"

		-- ANIMALS
		rabbits = "default", 			-- "never", "rare", "default", "often", "always"
		moles = "default", 			-- "never", "rare", "default", "often", "always"
		butterfly = "never", 			-- "never", "rare", "default", "often", "always"
		birds = "never", 			-- "never", "rare", "default", "often", "always"
		buzzard = "never", 			-- "never", "rare", "default", "often", "always"
		catcoon = "default", 			-- "never", "rare", "default", "often", "always"
		perd = "never", 			-- "never", "rare", "default", "often", "always"
		pigs = "default", 			-- "never", "rare", "default", "often", "always"
		lightninggoat = "default", 			-- "never", "rare", "default", "often", "always"
		beefalo = "often", 			-- "never", "rare", "default", "often", "always"
		beefaloheat = "default", 			-- "never", "rare", "default", "often", "always"
		hunt = "often", 			-- "never", "rare", "default", "often", "always"
		alternatehunt = "default", 			-- "never", "rare", "default", "often", "always"
		penguins = "often", 			-- "never", "rare", "default", "often", "always"
		cave_ponds = "never", 			-- "never", "rare", "default", "often", "always"
		ponds = "default", 			-- "never", "rare", "default", "often", "always"
		bees = "never", 			-- "never", "rare", "default", "often", "always"
		angrybees = "never", 			-- "never", "rare", "default", "often", "always"
		tallbirds = "default", 			-- "never", "rare", "default", "often", "always"
		slurper = "never", 			-- "never", "rare", "default", "often", "always"
		bunnymen = "never", 			-- "never", "rare", "default", "often", "always"
		slurtles = "never", 			-- "never", "rare", "default", "often", "always"
		rocky = "never", 			-- "never", "rare", "default", "often", "always"
		monkey = "never", 			-- "never", "rare", "default", "often", "always"

		-- MONSTERS
		spiders = "never", 			-- "never", "rare", "default", "often", "always"
		cave_spiders = "never", 			-- "never", "rare", "default", "often", "always"
		hounds = "never", 			-- "never", "rare", "default", "often", "always"
		houndmound = "default", 			-- "never", "rare", "default", "often", "always"
		merm = "never", 			-- "never", "rare", "default", "often", "always"
		tentacles = "never", 			-- "never", "rare", "default", "often", "always"
		chess = "never", 			-- "never", "rare", "default", "often", "always"
		lureplants = "never", 			-- "never", "rare", "default", "often", "always"
		walrus = "default", 			-- "never", "rare", "default", "often", "always"
		liefs = "default", 			-- "never", "rare", "default", "often", "always"
		deciduousmonster = "often", 			-- "never", "rare", "default", "often", "always"
		krampus = "often", 			-- "never", "rare", "default", "often", "always"
		bearger = "never", 			-- "never", "rare", "default", "often", "always"
		deerclops = "default", 			-- "never", "rare", "default", "often", "always"
		goosemoose = "never", 			-- "never", "rare", "default", "often", "always"
		dragonfly = "never", 			-- "never", "rare", "default", "often", "always"
		bats = "never", 			-- "never", "rare", "default", "often", "always"
		fissure = "never", 			-- "never", "rare", "default", "often", "always"
		worms = "never", 			-- "never", "rare", "default", "often", "always"
	},
}

