STRINGS = GLOBAL.STRINGS
RECIPETABS = GLOBAL.RECIPETABS
Recipe = GLOBAL.Recipe
Ingredient = GLOBAL.Ingredient
TECH = GLOBAL.TECH

TUNING.KRAMPUS_HEALTH = 3000
TUNING.KRAMPUS_SACK_DROP_RATE = 0.50

TUNING.KRAMPUS_DAMAGE = 25
KRAMPUS_ATTACK_PERIOD = 0.6


