STRINGS = GLOBAL.STRINGS
RECIPETABS = GLOBAL.RECIPETABS
Recipe = GLOBAL.Recipe
Ingredient = GLOBAL.Ingredient
TECH = GLOBAL.TECH

--AddRecipe("nightlight", {Ingredient("goldnugget", 16), Ingredient("nightmarefuel", 12),Ingredient("redgem", 2)}, RECIPETABS.MAGIC,  TECH.MAGIC_TWO, "nightlight_placer")

TUNING.SanityPerSwing = 1
TUNING.SwordSanityDrain = 0

TUNING.ARMOR_SANITY_DMG_AS_SANITY = 0.1
TUNING.ArmourSanityDrain = 0

TUNING.NIGHTLIGHT_FUEL_MAX_DAYS = 60
TUNING.NIGHTLIGHT_FUEL_SAY_PERIOD = 120

TUNING.NightmareFuelFuel = TUNING.TOTAL_DAY_TIME*(TUNING.NIGHTLIGHT_FUEL_MAX_DAYS/4)
TUNING.NIGHTLIGHT_FUEL_MAX = TUNING.TOTAL_DAY_TIME*TUNING.NIGHTLIGHT_FUEL_MAX_DAYS
TUNING.NightmareLightSanityAura = 0

TUNING.NIGHTLIGHT_FUEL_START = 0
